### ISSUE TITLE
can we remove some character before encrypted to (3DES)?

### ISSUE THREAD

**Issue by NTMS2017** [johnpryan/tripledes-dart#4]
Hi there,

Its a great plugin and its also work with Aqueduct frame work. But once I encrypted data and result has + / type characters I not working in Aqueduct frame work. So how can we exclude certain characters before encrypted our data?

**Comment by johnpryan** [comment]
Yes, have you tried doing a simple replaceAll? https://api.dartlang.org/stable/1.24.3/dart-core/String/replaceAll.html

**Comment by NTMS2017** [comment]
Thanks, but I was talking about 65 character in the library. When I look at it has a + / and = character en of it. After capital alphabet, lover case alphabet and the number from 0 to 9.  problem was / character. aqueduct thinks another route. I sort out change in the receiving method. 

By the way I am trying to use triplexes in Fluter as well. Does it work? Do you have a any new update for the plugin like supporting Dart 2 etc... And lastly it solved my problem using this plugin.

Kind Regards.

**Comment by johnpryan** [comment]
It sounds like you need to make the string url-safe for aqueduct, am I understanding correctly?

**Comment by johnpryan** [comment]
For url-safe strings, you can base64 encode the string

**Comment by NTMS2017** [comment]
Thanks John, first of all it was my error that I didn't know how to use aqueduct correctly. for my api if use ex: 127.0.0.1:8888/login/* its working ( * ) accepts rest of the value as a single text. And yes, I need string url-safe. I manage to make it. But I have another problem that I need to hide the key value with aqueduct. I will try to use in DMZ Ubuntu 16.04 LTS or 18.04 LTS and somehow I need to secure the aqueduct project folder. Kind Reagards

**Comment by johnpryan** [comment]
Good luck!
